name: Some test pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test_job:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run a test script
          run: echo "This is a test script running in the GitHub Actions workflow."
